In [1]:
from si.data.dataset import Dataset
import numpy as np
from si.io.csv_file import read_csv

In [2]:
caminho = 'C:\\Percurso Académico\\Mestrado em Bioinformática - UMinho\\2023-2024\\02 Disciplinas\\1º Semestre\\03 Sistemas Inteligentes para a Bioinformática\\si\\datasets\\iris\\iris.csv'
ficheiroCSV = read_csv(caminho, ',', True, True)

#print(ficheiroCSV.X)
#print("Y")
#print(ficheiroCSV.y)
print(ficheiroCSV.get_mean())

penultimaColuna = ficheiroCSV.X[:, -2]

#print(penultimaColuna)

dimensao = penultimaColuna.shape

#print(dimensao)



[5.84333333 3.054      3.75866667 1.19866667]


In [3]:
# Alínes 1.3)

amostra = ficheiroCSV.X[-10:,:-1]

print(amostra)

# numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

media = np.mean(amostra, 0)

print(media)

print(ficheiroCSV.features)

[[6.7 3.1 5.6]
 [6.9 3.1 5.1]
 [5.8 2.7 5.1]
 [6.8 3.2 5.9]
 [6.7 3.3 5.7]
 [6.7 3.  5.2]
 [6.3 2.5 5. ]
 [6.5 3.  5.2]
 [6.2 3.4 5.4]
 [5.9 3.  5.1]]
[6.45 3.03 5.33]
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')


In [4]:
# Alínes 1.4)
ficheiroCSV = read_csv(caminho, ',', True)


print("linha com todosvalores menores que 6:")
amostra=ficheiroCSV.X[:,:-1]
#print(amostra)
lista=[]
for am in amostra:
    ind=np.where(am<=6)
    if len(am[ind])== 4:
        lista.append(am[ind])
amostraMenor6 = np.array(lista)
print(lista)
print (amostraMenor6)
print (len(amostraMenor6))
print (np.shape(amostraMenor6))


linha com todosvalores menores que 6:
[array([5.1, 3.5, 1.4, 0.2], dtype=object), array([4.9, 3.0, 1.4, 0.2], dtype=object), array([4.7, 3.2, 1.3, 0.2], dtype=object), array([4.6, 3.1, 1.5, 0.2], dtype=object), array([5.0, 3.6, 1.4, 0.2], dtype=object), array([5.4, 3.9, 1.7, 0.4], dtype=object), array([4.6, 3.4, 1.4, 0.3], dtype=object), array([5.0, 3.4, 1.5, 0.2], dtype=object), array([4.4, 2.9, 1.4, 0.2], dtype=object), array([4.9, 3.1, 1.5, 0.1], dtype=object), array([5.4, 3.7, 1.5, 0.2], dtype=object), array([4.8, 3.4, 1.6, 0.2], dtype=object), array([4.8, 3.0, 1.4, 0.1], dtype=object), array([4.3, 3.0, 1.1, 0.1], dtype=object), array([5.8, 4.0, 1.2, 0.2], dtype=object), array([5.7, 4.4, 1.5, 0.4], dtype=object), array([5.4, 3.9, 1.3, 0.4], dtype=object), array([5.1, 3.5, 1.4, 0.3], dtype=object), array([5.7, 3.8, 1.7, 0.3], dtype=object), array([5.1, 3.8, 1.5, 0.3], dtype=object), array([5.4, 3.4, 1.7, 0.2], dtype=object), array([5.1, 3.7, 1.5, 0.4], dtype=object), array([4.6, 3.6

In [5]:
# Alinea 2.1)

print("linha com todas amostras com label diferente de \"Iris-setosa\":")
lista=[]
for x in ficheiroCSV.X:
    if x[4]!= 'Iris-setosa':
        lista.append(x)
resultado=np.array (lista)
print(resultado)
print(len(resultado))

linha com todas amostras com label diferente de "Iris-setosa":
[[7.0 3.2 4.7 1.4 'Iris-versicolor']
 [6.4 3.2 4.5 1.5 'Iris-versicolor']
 [6.9 3.1 4.9 1.5 'Iris-versicolor']
 [5.5 2.3 4.0 1.3 'Iris-versicolor']
 [6.5 2.8 4.6 1.5 'Iris-versicolor']
 [5.7 2.8 4.5 1.3 'Iris-versicolor']
 [6.3 3.3 4.7 1.6 'Iris-versicolor']
 [4.9 2.4 3.3 1.0 'Iris-versicolor']
 [6.6 2.9 4.6 1.3 'Iris-versicolor']
 [5.2 2.7 3.9 1.4 'Iris-versicolor']
 [5.0 2.0 3.5 1.0 'Iris-versicolor']
 [5.9 3.0 4.2 1.5 'Iris-versicolor']
 [6.0 2.2 4.0 1.0 'Iris-versicolor']
 [6.1 2.9 4.7 1.4 'Iris-versicolor']
 [5.6 2.9 3.6 1.3 'Iris-versicolor']
 [6.7 3.1 4.4 1.4 'Iris-versicolor']
 [5.6 3.0 4.5 1.5 'Iris-versicolor']
 [5.8 2.7 4.1 1.0 'Iris-versicolor']
 [6.2 2.2 4.5 1.5 'Iris-versicolor']
 [5.6 2.5 3.9 1.1 'Iris-versicolor']
 [5.9 3.2 4.8 1.8 'Iris-versicolor']
 [6.1 2.8 4.0 1.3 'Iris-versicolor']
 [6.3 2.5 4.9 1.5 'Iris-versicolor']
 [6.1 2.8 4.7 1.2 'Iris-versicolor']
 [6.4 2.9 4.3 1.3 'Iris-versicolor']
 [6.6 3.0 4.

In [6]:
caminho = 'C:\\Percurso Académico\\Mestrado em Bioinformática - UMinho\\2023-2024\\02 Disciplinas\\1º Semestre\\03 Sistemas Inteligentes para a Bioinformática\\si\\datasets\\iris\\iris.csv'
ficheiroCSV = read_csv(caminho, ',', True, True)
print(ficheiroCSV.X)
print(ficheiroCSV.y)
print(ficheiroCSV.dropna())




[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.